### PR TITLE
feat: Change configure to mjs with google zx

### PR DESCRIPTION
**Pull request by aumer-amr**
This PR changes the current bash script of configure to a (bit) more structured and more maintainable script. At this moment it's a rewrite without to many changes (some QOL).

QOL changes:
- Checking if verify was run before configure
- Checking of config was changed between verify and configure
- Writing output to log for easier debugging/sharing
- Debug option
- Configuration checking (missing required fields, regex patterns)

To make it work:
1. pull branch
2. make sure you have latest node lts
3. run 'npm i'
4. run 'npm i -g zx'
5. run 'chmod +x configure.mjs'
6. run './configure.mjs' to see the usage

(woops forgot the PR)

### CODE REVIEW

**Comment by onedr0p** [comment]
Very nice work! I hope people aren't put off by us switching to zx. I have a few comments though that might need to be addressed.

- Add zx to brew taskfile, the package name is `zx`
- Update the taskfile to have `task verify` and `task configure` use zx
- The weave secret name and admin data should be reverted, the chart expects the secret with that name and data.
- Need to update the readme with docs on installing zx outside brew.

**Comment by mrueg** [comment]
Not a super huge fan of this change to be honest.

* Adds a whole new language stack vs. a tool (bash) that exists on all hosts.
* More difficult to extend and customize (in bash, I can simply add a `source custom.sh` to it)
* eventually the configure step is mainly simple templating. Why do I need a whole node stack for this?

Have you considered moving the config step itself into an ansible playbook that you can run locally?

**Comment by aumer-amr** [comment]
> * Adds a whole new language stack vs. a tool (bash) that exists on all hosts.
You already install quite a few things with this template, by adding this stack we can also remove a few other brews, for example jq. The language i'm not too worried about, not many people would customize their configuration file in the first place, and zx/node is easier to get into if they decide to do that (and are unfamiliar with bash scripting).

> * More difficult to extend and customize (in bash, I can simply add a `source custom.sh` to it)
You can easily do `require('./custom.js')` to it, so it is as simple as `source custom.sh`. We can even build hooks into this script in the future, so if you want to do a custom action at X step, or a custom action on it's own that's completely possible.

> * eventually the configure step is mainly simple templating. Why do I need a whole node stack for this?
As now it's a rewrite with some QOL, we discussed this to be improved afterwards (it's also one big file). So this is step 1 of improving the whole configuration method.

> Have you considered moving the config step itself into an ansible playbook that you can run locally?
onedr0p wants to move away from ansible at some point (future), hence why it's not put into an ansible playbook.

**Comment by onedr0p** [comment]
I wonder if we could support both `bash` and `zx` scripts for awhile while keeping feature parity and maybe deprecate bash after awhile?

I never did give Ansible a thought for building out the templating piece but I can't imagine it would be as flexible as bash/zx, but maybe it could be considered? I can see templating being easier in certain aspects but other logic being written in a way that's hard to read & write.

It's really hard to choose a tool for doing this that everyone would agree upon.

**Comment by onedr0p** [comment]
> Have you considered moving the config step itself into an ansible playbook that you can run locally?

@mrueg I'd be interested in seeing an MVP of this if you have some spare cycles.

**Comment by mrueg** [comment]
@onedr0p looks like you beat me to it! Thanks for https://github.com/onedr0p/flux-cluster-template/pull/822 I like where it is going. :)

**Comment by onedr0p** [comment]
Thanks for giving this a shot @aumer-amr hopefully your new found zx skills will be usable infuture projects 🙂

**Pull request closed without merging**
