### PR TITLE
feat(pre-commit): add renovate check to pre-commit hooks

### PR DESCRIPTION
**Pull request by willianpaixao**
Sometimes updating the renovate config file can be hard, so it's good to have a check before committing an invalid one.

Reference: https://docs.renovatebot.com/config-validation/

### CODE REVIEW

**Comment by onedr0p** [comment]
While I like the thought behind this, the updates to that precommit hook are going to be daily if not more than once a day. I'm not sure the best way to approach that was I don't want to deal with commits spamming the repo or PRs spamming my notifications 😕

**Comment by onedr0p** [comment]
It's also with noting that the GHA always uses the latest version of Renovate which could make this precommit hook fall behind what it is actually ran against.

**Comment by willianpaixao** [comment]
True, didn'r think about it, maybe restrict or pin the version of the hook? Let me think a bit.

**Comment by alex-matthews** [comment]
On this general subject, is the current and only pre-commit hook still useful or has editorconfig made it redundant?

**Comment by onedr0p** [comment]
Good point, it's probably not really worth it anymore because of editorconfig. I'm not using precommit anymore for my personal projects.

**Pull request closed without merging**
