### PR TITLE
feat: move kubernetes dir into templates to support jinja2 across all files

### PR DESCRIPTION
**Pull request by onedr0p**
This PR moves the kubernetes dir into the templates directory and renames the files to `.yaml.j2`. This is being done to support templating across all the files in the kubernetes directory and will give us the ability to make this more modular.

### CODE REVIEW

**Comment by onedr0p** [comment]
@mrueg if you have a minute I'm looking for feedback on if this a good idea or not.

**Comment by onedr0p** [comment]
I believe this is a good enough first pass, most file changes here are just a rename as the root kubernetes folder doesn't exist anymore.

**Comment by mrueg** [comment]
@onedr0p I like the idea, it might be a bit more difficult for folks to grasp, as it's adding another layer of abstraction though

**Comment by onedr0p** [comment]
I think overall it will work out, I just need to add more documentation around it

It was nice adding support for this https://github.com/onedr0p/flux-cluster-template/pull/837

**Pull request merged**
