### PR TITLE
bring setup steps under one L2 heading

### PR DESCRIPTION
**Pull request by alex-matthews**
For easier reference and to make room for other L2 headings such as **"Usage"** and **"FAQs"**.

### CODE REVIEW

**Comment by onedr0p** [comment]
Maybe instead of Step we use a different name since there would be substeps and subsubsteps?

**Comment by alex-matthews** [comment]
We could use Stage, but there are no L4 headings that need to be referred to as substeps. Your call.

**Comment by onedr0p** [comment]
The substeps would be the ones with letters, e.g. 2a, 2b, 2c, etc..

Stage or section is probably fine unless you come up with a better name

**Comment by alex-matthews** [comment]
Stage sounds good. Section sounds unnatural to me, e.g. "There are 6 sections to getting a Flux-managed cluster up and running."

One note on substeps: a good way to refer to them would be "Step 2b". And subsubsteps: "Step 3c(iii)"

**Review by onedr0p — APPROVED** [review]

**Pull request merged**
