### PR TITLE
Update cluster-prepare to include group_vars

### PR DESCRIPTION
**Pull request by PrymalInstynct**
**Description of the change**

 Added include_vars task which I found as the fix to force the `Packages | Remove leaf packages` task to read `group_vars/kubernetes/os.yml` for its list of packages to install.

**Benefits**

Allows playbook to complete successfully

**Possible drawbacks**

There might be a better way

**Applicable issues**

- Discussed in (#499) but no formal issue opened

**Additional information**

Sorry for closing the previous PR, I wanted to get this on a clean branch

### CODE REVIEW

**Comment by onedr0p** [comment]
I tried without this on my production cluster and it picked up the vars automatically. Can you share your `host.yml` and `provision/ansible` folder tree, and how you are running the playbook?

**Comment by PrymalInstynct** [comment]
```
# cat provision/ansible/inventory/hosts.yml 
---
kubernetes:
  children:
    master:
      hosts:
        k8s-control-dev-0:
          ansible_host: 10.10.111.10
        k8s-control-dev-1:
          ansible_host: 10.10.111.11
        k8s-control-dev-2:
          ansible_host: 10.10.111.12
    worker:
      hosts:
        k8s-worker-dev-3:
          ansible_host: 10.10.111.13
        k8s-worker-dev-4:
          ansible_host: 10.10.111.14
```

```
# tree provision/ansible/
provision/ansible/
|-- inventory
|   |-- group_vars
|   |   |-- kubernetes
|   |   |   |-- k3s.yml
|   |   |   |-- kube-vip.yml
|   |   |   `-- os.yml
|   |   |-- master
|   |   |   `-- k3s.yml
|   |   `-- worker
|   |       `-- k3s.yml
|   |-- host_vars
|   |   |-- k8s-control-dev-0.sops.yml
|   |   |-- k8s-control-dev-1.sops.yml
|   |   |-- k8s-control-dev-2.sops.yml
|   |   |-- k8s-worker-dev-3.sops.yml
|   |   `-- k8s-worker-dev-4.sops.yml
|   `-- hosts.yml
|-- playbooks
|   |-- cluster-harden.yml
|   |-- cluster-installation.yml
|   |-- cluster-nuke.yml
|   |-- cluster-prepare.yml
|   |-- cluster-reboot.yml
|   `-- templates
|       |-- calico-installation.yaml.j2
|       `-- kube-vip-daemonset.yaml.j2
`-- requirements.yml
```

**Comment by PrymalInstynct** [comment]
As an FYI I built a brand new cluster and got the exact same result with the baselined `cluster-prepare.yml. However, when I added my change back into the playbook it worked fine.

**Comment by onedr0p** [comment]
I've tested this out and was also helping another person and we both didn't run into this issue. I'm really curious why it's happening on your work station.

**Comment by PrymalInstynct** [comment]
Yeah, it is strange. My dev box is Fedora 36 Workstation and my cluster is being installed onto 5x Fedora 36 Server instances.

Side note: that MegaLinter error is weird...Cant find community.general.timezone as a "real" module.

**Comment by onedr0p** [comment]
The person I was helping was also using Fedora. I'm going to go ahead and close this PR but if it comes up again or many others complain we can circle back to it.

**Pull request closed without merging**
